# site settings
title: Lyle Hubbard
subtitle: Internet Technology Consultation
email: lhubbard@pdx.edu

description: Background Skillset
baseurl:  # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
author:
street_address: 
city: Portland
state: Oregon
zip_code: 
country: United States of America
#phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"

tiles-count: 6

tile_display_order: "blog;cloudtech;ml;"

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 

googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/lhubbard01
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
